version: '3.9'

services:
  postgres:
    container_name: encacap-re-apis-postgres
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    env_file:
      - .env.development
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - encacap-re-apis-network

  dev:
    container_name: encacap-re-apis-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
    environment:
      - DB_HOST=postgres
    networks:
      - encacap-re-apis-network
    depends_on:
      - postgres

networks:
  encacap-re-apis-network:
    driver: bridge

volumes:
  postgres:
